### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by ddansab** [cortesg/microblog#3]
Create "delete" function (destroy)

**Comment by cortesg** [comment]
"It's destroy and destroy_all methods, like

user.destroy
User.find(15).destroy
User.destroy(15)
User.where(age: 20).destroy_all
User.destroy_all(age: 20)
Alternatively you can use delete and delete_all which won't enforce :before_destroy and :after_destroy callbacks or any dependent association options."

-from StackOverflow

**Comment by cortesg** [comment]
working destory function on gino branch commit 18
